it.geosolutions.jgridshift--jgridshift-core--1.3=GNU Lesser General Public License (LGPL)
org.apache.xml--xml-commons-resolver--1.2=Apache License
picocontainer--picocontainer--1.2=BSD 3-Clause License
